export const mockUpcomingExams = [
  {
    id: "EX001",
    title: "React.js Development",
    subject: "Full Stack Web Development",
    date: "2026-04-20",
    time: "10:00 AM - 12:00 PM",
    duration: "120 mins",
    totalMarks: 100,
    mode: "Online",
    location: "Lab A",
  },
  {
    id: "EX002",
    title: "Flutter Basics",
    subject: "Mobile App Development",
    date: "2026-04-25",
    time: "2:00 PM - 4:00 PM",
    duration: "120 mins",
    totalMarks: 100,
    mode: "Online",
    location: "Lab B",
  },
]

export const mockExamSchedule = [
  {
    id: "ES001",
    title: "React.js Development",
    subject: "Full Stack Web Development",
    date: "2026-04-20",
    time: "10:00 AM - 12:00 PM",
    duration: "120 mins",
    location: "Lab A",
    mode: "Online",
  },
  {
    id: "ES002",
    title: "Flutter Basics",
    subject: "Mobile App Development",
    date: "2026-04-25",
    time: "2:00 PM - 4:00 PM",
    duration: "120 mins",
    location: "Lab B",
    mode: "Online",
  },
  {
    id: "ES003",
    title: "Database Design",
    subject: "Database Management",
    date: "2026-04-30",
    time: "9:00 AM - 11:00 AM",
    duration: "120 mins",
    location: "Room 101",
    mode: "Offline",
  },
  {
    id: "ES004",
    title: "Node.js & Express",
    subject: "Full Stack Web Development",
    date: "2026-05-05",
    time: "11:00 AM - 1:00 PM",
    duration: "120 mins",
    location: "Lab C",
    mode: "Online",
  },
]

export const mockExamResults = [
  {
    id: "ER001",
    subject: "JavaScript Fundamentals",
    course: "Full Stack Web Development",
    date: "2026-03-15",
    marks: 88,
    totalMarks: 100,
    percentage: 88,
    grade: "A",
    status: "Passed",
    remarks: "Excellent performance",
  },
  {
    id: "ER002",
    subject: "HTML & CSS",
    course: "Full Stack Web Development",
    date: "2026-03-28",
    marks: 95,
    totalMarks: 100,
    percentage: 95,
    grade: "A+",
    status: "Passed",
    remarks: "Outstanding",
  },
  {
    id: "ER003",
    subject: "Dart Programming",
    course: "Mobile App Development",
    date: "2026-03-10",
    marks: 82,
    totalMarks: 100,
    percentage: 82,
    grade: "B+",
    status: "Passed",
    remarks: "Good work",
  },
  {
    id: "ER004",
    subject: "Database Design",
    course: "Database Management",
    date: "2026-02-20",
    marks: 91,
    totalMarks: 100,
    percentage: 91,
    grade: "A+",
    status: "Passed",
    remarks: "Excellent understanding",
  },
  {
    id: "ER005",
    subject: "Node.js & Express",
    course: "Full Stack Web Development",
    date: "2026-02-05",
    marks: 78,
    totalMarks: 100,
    percentage: 78,
    grade: "B",
    status: "Passed",
    remarks: "Satisfactory",
  },
]

export const mockExamStats = {
  upcomingExams: 2,
  completedExams: 5,
  averageScore: 87,
}
