import type {
  StaffRecord,
  PayrollRecord,
  LeaveRequestRecord,
  GenericRecordItem,
  TeacherRatingRecord,
  DepartmentCardRecord,
} from "../types"

export const staffStats = {
  totalStaff: 111,
  active: 108,
  teachers: 74,
  supportStaff: 37,
}

export const staffDirectoryStore: StaffRecord[] = [
  {
    id: "STF-001",
    name: "Dr. Amara Singh",
    role: "Mathematics Teacher",
    initial: "D",
    initialColor: "bg-indigo-600",
    department: "Sciences",
    email: "amara.singh@school.edu",
    phone: "+91 98765 11111",
    joined: "Aug 12, 2019",
    status: "active",
    type: "Teacher",
  },
  {
    id: "STF-002",
    name: "Ms. Claire Fontaine",
    role: "English Teacher",
    initial: "M",
    initialColor: "bg-indigo-600",
    department: "Languages",
    email: "claire.f@school.edu",
    phone: "+33 6 12 34 56 78",
    joined: "Jan 4, 2021",
    status: "active",
    type: "Teacher",
  },
  {
    id: "STF-003",
    name: "Mr. Emmanuel Obi",
    role: "Physical Education",
    initial: "M",
    initialColor: "bg-indigo-600",
    department: "Sports",
    email: "e.obi@school.edu",
    phone: "+234 803 456 7890",
    joined: "Mar 15, 2020",
    status: "active",
    type: "Teacher",
  },
  {
    id: "STF-004",
    name: "Mrs. Nadia Al-Farsi",
    role: "Science Teacher",
    initial: "M",
    initialColor: "bg-indigo-600",
    department: "Sciences",
    email: "nadia.af@school.edu",
    phone: "+968 9234 5678",
    joined: "Sep 1, 2022",
    status: "active",
    type: "Teacher",
  },
  {
    id: "STF-005",
    name: "Mr. Tomás Rivera",
    role: "History Teacher",
    initial: "M",
    initialColor: "bg-indigo-600",
    department: "Humanities",
    email: "tomas.r@school.edu",
    phone: "+52 55 1234 5678",
    joined: "Jul 20, 2018",
    status: "inactive",
    type: "Teacher",
  },
  {
    id: "STF-006",
    name: "Ms. Yuki Tanaka",
    role: "Art Teacher",
    initial: "M",
    initialColor: "bg-indigo-600",
    department: "Creative Arts",
    email: "yuki.t@school.edu",
    phone: "+81 90 1234 5678",
    joined: "Feb 9, 2023",
    status: "active",
    type: "Teacher",
  },
]

export const payrollStore: PayrollRecord[] = [
  {
    id: "STF-001",
    name: "Dr. Amara Singh",
    role: "Mathematics Teacher",
    basicSalary: 5500,
    allowances: 800,
    deductions: 620,
    netSalary: 5680,
    status: "Processing",
  },
  {
    id: "STF-002",
    name: "Ms. Claire Fontaine",
    role: "English Teacher",
    basicSalary: 5200,
    allowances: 700,
    deductions: 580,
    netSalary: 5320,
    status: "Processing",
  },
  {
    id: "STF-003",
    name: "Mr. Emmanuel Obi",
    role: "Physical Education",
    basicSalary: 4800,
    allowances: 600,
    deductions: 520,
    netSalary: 4880,
    status: "Processing",
  },
  {
    id: "STF-004",
    name: "Mrs. Nadia Al-Farsi",
    role: "Science Teacher",
    basicSalary: 5100,
    allowances: 750,
    deductions: 560,
    netSalary: 5290,
    status: "Processing",
  },
]

export const leaveRequestStore: LeaveRequestRecord[] = [
  {
    id: "LR-001",
    staffMember: "Dr. Amara Singh",
    leaveType: "Sick Leave",
    from: "Aug 4, 2026",
    to: "Aug 5, 2026",
    days: 2,
    reason: "Medical appointment",
    status: "Pending",
  },
  {
    id: "LR-002",
    staffMember: "Ms. Yuki Tanaka",
    leaveType: "Annual Leave",
    from: "Aug 10, 2026",
    to: "Aug 14, 2026",
    days: 5,
    reason: "Family vacation",
    status: "Approved",
  },
  {
    id: "LR-003",
    staffMember: "Mr. Emmanuel Obi",
    leaveType: "Emergency Leave",
    from: "Aug 1, 2026",
    to: "Aug 2, 2026",
    days: 2,
    reason: "Family emergency",
    status: "Approved",
  },
  {
    id: "LR-004",
    staffMember: "Mrs. Nadia Al-Farsi",
    leaveType: "Study Leave",
    from: "Aug 18, 2026",
    to: "Aug 22, 2026",
    days: 5,
    reason: "Professional development workshop",
    status: "Pending",
  },
]

export const leaveTypeStore: GenericRecordItem[] = [
  { id: "1", name: "Sick Leave", details: "Medical and health appointments", date: "Aug 1, 2026", status: "Active" },
  { id: "2", name: "Annual Leave", details: "Paid vacation and annual entitlement", date: "Aug 1, 2026", status: "Active" },
  { id: "3", name: "Emergency Leave", details: "Unforeseen emergencies and bereavement", date: "Aug 1, 2026", status: "Active" },
  { id: "4", name: "Study Leave", details: "Professional development and exams", date: "Aug 1, 2026", status: "Active" },
]

export const teachersRatingStore: GenericRecordItem[] = [
  { id: "1", name: "Dr. Amara Singh", details: "Rating: 4.8/5.0 — 37 reviews", date: "Aug 1, 2026", status: "Active" },
  { id: "2", name: "Ms. Claire Fontaine", details: "Rating: 4.6/5.0 — 34 reviews", date: "Aug 1, 2026", status: "Active" },
  { id: "3", name: "Mr. Emmanuel Obi", details: "Rating: 4.7/5.0 — 71 reviews", date: "Aug 1, 2026", status: "Active" },
  { id: "4", name: "Mrs. Nadia Al-Farsi", details: "Rating: 4.5/5.0 — 30 reviews", date: "Aug 1, 2026", status: "Active" },
  { id: "5", name: "Ms. Yuki Tanaka", details: "Rating: 4.9/5.0 — 63 reviews", date: "Aug 1, 2026", status: "Active" },
]

export const teacherRatingOverviewStore: TeacherRatingRecord[] = [
  {
    id: "TR-001",
    name: "Dr. Amara Singh",
    role: "Mathematics Teacher",
    initial: "D",
    initialColor: "bg-indigo-600",
    department: "Sciences",
    rating: 4.8,
    reviewsCount: 37,
    status: "Active",
  },
  {
    id: "TR-002",
    name: "Ms. Claire Fontaine",
    role: "English Teacher",
    initial: "M",
    initialColor: "bg-indigo-600",
    department: "Languages",
    rating: 4.6,
    reviewsCount: 34,
    status: "Active",
  },
  {
    id: "TR-003",
    name: "Mr. Emmanuel Obi",
    role: "Physical Education",
    initial: "M",
    initialColor: "bg-indigo-600",
    department: "Sports",
    rating: 4.7,
    reviewsCount: 71,
    status: "Active",
  },
  {
    id: "TR-004",
    name: "Mrs. Nadia Al-Farsi",
    role: "Science Teacher",
    initial: "M",
    initialColor: "bg-indigo-600",
    department: "Sciences",
    rating: 4.5,
    reviewsCount: 30,
    status: "Active",
  },
  {
    id: "TR-005",
    name: "Ms. Yuki Tanaka",
    role: "Art Teacher",
    initial: "M",
    initialColor: "bg-indigo-600",
    department: "Creative Arts",
    rating: 4.9,
    reviewsCount: 63,
    status: "Active",
  },
]

export const departmentCardStore: DepartmentCardRecord[] = [
  {
    id: "DEP-001",
    name: "Sciences",
    head: "Dr. Amara Singh",
    staffCount: 12,
    subjects: ["Mathematics", "Physics", "Chemistry", "Biology"],
  },
  {
    id: "DEP-002",
    name: "Languages",
    head: "Ms. Claire Fontaine",
    staffCount: 8,
    subjects: ["English", "French", "Spanish"],
  },
  {
    id: "DEP-003",
    name: "Humanities",
    head: "Mr. Tomás Rivera",
    staffCount: 6,
    subjects: ["History", "Geography", "Civics"],
  },
  {
    id: "DEP-004",
    name: "Creative Arts",
    head: "Ms. Yuki Tanaka",
    staffCount: 4,
    subjects: ["Art", "Music", "Drama"],
  },
  {
    id: "DEP-005",
    name: "Sports",
    head: "Mr. Emmanuel Obi",
    staffCount: 5,
    subjects: ["Physical Education", "Sports Training"],
  },
]

export const departmentStore: GenericRecordItem[] = [
  { id: "1", name: "Sciences", details: "Mathematics, Physics, Chemistry, Biology", date: "Aug 1, 2026", status: "Active" },
  { id: "2", name: "Languages", details: "English, French, Spanish, Literature", date: "Aug 1, 2026", status: "Active" },
  { id: "3", name: "Humanities", details: "History, Geography, Social Studies", date: "Aug 1, 2026", status: "Active" },
  { id: "4", name: "Creative Arts", details: "Fine Arts, Music, Drama", date: "Aug 1, 2026", status: "Active" },
  { id: "5", name: "Sports", details: "Physical Education, Athletics", date: "Aug 1, 2026", status: "Active" },
]

export const designationStore: GenericRecordItem[] = [
  { id: "1", name: "Head of Department (HOD)", details: "Academic and faculty leadership", date: "Aug 1, 2026", status: "Active" },
  { id: "2", name: "Senior Teacher", details: "Senior curriculum instruction", date: "Aug 1, 2026", status: "Active" },
  { id: "3", name: "Assistant Teacher", details: "Classroom instruction and tutoring", date: "Aug 1, 2026", status: "Active" },
  { id: "4", name: "Lab Instructor", details: "Practical laboratory coordination", date: "Aug 1, 2026", status: "Active" },
]

export const disabledStaffStore: GenericRecordItem[] = [
  { id: "1", name: "Mr. Tomás Rivera", details: "Inactive faculty profile — on sabbatical", date: "Jul 20, 2026", status: "Inactive" },
]

