import type {
  NoticeRecord,
  CommunicationStats,
  CommunicationLogRecord,
  ScheduledBroadcastRecord,
  CommunicationTemplateRecord,
  LoginCredentialRecord,
} from "../types"

// In-memory mock store for Communication module

export const noticeStore: NoticeRecord[] = [
  {
    id: "NTC-001",
    title: "Annual Sports Day 2026 — Schedule & Guidelines",
    audience: "All",
    date: "Aug 1, 2026",
    priority: "High",
    status: "Published",
    content: "The Annual Sports Day 2026 will be held on August 15. All students, parents, and faculty are cordially invited to participate.",
  },
  {
    id: "NTC-002",
    title: "Mid-Term Examination Datesheet Announced",
    audience: "Students",
    date: "Jul 28, 2026",
    priority: "High",
    status: "Published",
    content: "The mid-term examination timetable for grades 6 to 12 is now available. Please download the schedule from the student portal.",
  },
  {
    id: "NTC-003",
    title: "Parent-Teacher Meeting for Grade 10",
    audience: "Parents",
    date: "Jul 25, 2026",
    priority: "Medium",
    status: "Published",
    content: "Mandatory Parent-Teacher consultation sessions will take place on Saturday, August 5 from 9:00 AM to 1:00 PM in the main auditorium.",
  },
  {
    id: "NTC-004",
    title: "Staff Professional Development Workshop",
    audience: "Staff",
    date: "Jul 20, 2026",
    priority: "Low",
    status: "Published",
    content: "All teaching and non-teaching staff must attend the digital pedagogy and campus security training workshop this Thursday.",
  },
  {
    id: "NTC-005",
    title: "Library Book Return Notice — Summer Term",
    audience: "Students",
    date: "Jul 18, 2026",
    priority: "Medium",
    status: "Draft",
    content: "All students are requested to return borrowed books prior to the summer recess to avoid overdue fines.",
  },
]

export const communicationStats: CommunicationStats = {
  emailsSent: "4,218",
  openRate: "78.4%",
  smsSent: "8,940",
  deliveryRate: "97.2%",
  totalRecipients: "2,198",
}

export const emailLogStore: CommunicationLogRecord[] = [
  {
    id: "EML-001",
    type: "Email",
    subject: "Fee Payment Reminder — August 2026",
    recipients: 312,
    sentAt: "Aug 1, 2026 09:00 AM",
    opens: "248 (79%)",
    status: "Delivered",
  },
  {
    id: "EML-002",
    type: "Email",
    subject: "Summer Break Schedule",
    recipients: 1342,
    sentAt: "Jul 30, 2026 10:30 AM",
    opens: "1,089 (81%)",
    status: "Delivered",
  },
  {
    id: "EML-003",
    type: "Email",
    subject: "Result Publication Notice",
    recipients: 1342,
    sentAt: "Jul 25, 2026 02:00 PM",
    opens: "1,201 (89%)",
    status: "Delivered",
  },
  {
    id: "EML-004",
    type: "Email",
    subject: "Parent-Teacher Meeting Invite",
    recipients: 856,
    sentAt: "Jul 20, 2026 08:00 AM",
    opens: "612 (71%)",
    status: "Partial",
  },
]

export const smsLogStore: CommunicationLogRecord[] = [
  {
    id: "SMS-001",
    type: "SMS",
    subject: "Urgent: School bus route delay today",
    recipients: 450,
    sentAt: "Aug 2, 2026 07:30 AM",
    opens: "448 (99%)",
    status: "Delivered",
  },
  {
    id: "SMS-002",
    type: "SMS",
    subject: "Exam hall ticket reminder for Grade 12",
    recipients: 210,
    sentAt: "Jul 29, 2026 11:15 AM",
    opens: "206 (98%)",
    status: "Delivered",
  },
  {
    id: "SMS-003",
    type: "SMS",
    subject: "Emergency closure advisory notice",
    recipients: 2198,
    sentAt: "Jul 15, 2026 06:00 AM",
    opens: "2,150 (97%)",
    status: "Delivered",
  },
]

export const scheduledBroadcastStore: ScheduledBroadcastRecord[] = [
  {
    id: "SCH-001",
    type: "Email",
    title: "First Term Progress Reports Release",
    recipients: "Parents (Grade 1-12)",
    scheduledFor: "Aug 15, 2026 09:00 AM",
    status: "Scheduled",
  },
  {
    id: "SCH-002",
    type: "SMS",
    title: "Independence Day Assembly Reminder",
    recipients: "All Students & Staff",
    scheduledFor: "Aug 14, 2026 06:00 PM",
    status: "Scheduled",
  },
]

export const emailTemplateStore: CommunicationTemplateRecord[] = [
  {
    id: "1",
    type: "Email",
    title: "Fee Reminder",
    subject: "Fee Payment Due — {month}",
    category: "Finance",
    lastUsed: "Aug 1, 2026",
    body: "Dear Parent,\n\nPlease be reminded that school fee payment for {month} is due. Please clear before the due date to avoid late charges.\n\nThank you,\nFinance Department",
    variables: ["month"],
    updatedAt: "Aug 1, 2026",
  },
  {
    id: "2",
    type: "Email",
    title: "Exam Result",
    subject: "Your Child's Exam Results Are Available",
    category: "Academic",
    lastUsed: "Jul 25, 2026",
    body: "Dear Parent,\n\nYour child's recent examination results have been published. Please log in to the student portal to review the grades and report card.\n\nWarm regards,\nAcademic Office",
    variables: [],
    updatedAt: "Jul 25, 2026",
  },
  {
    id: "3",
    type: "Email",
    title: "Event Invitation",
    subject: "You're Invited: {event_name}",
    category: "Events",
    lastUsed: "Jul 10, 2026",
    body: "Dear Community,\n\nWe cordially invite you to join us for {event_name}. We look forward to celebrating with you!\n\nBest regards,\nEvents Committee",
    variables: ["event_name"],
    updatedAt: "Jul 10, 2026",
  },
  {
    id: "4",
    type: "Email",
    title: "Leave Approval",
    subject: "Leave Application Status — {status}",
    category: "HR",
    lastUsed: "Jun 28, 2026",
    body: "Dear Staff Member,\n\nYour leave application status has been updated to: {status}.\n\nHuman Resources Department",
    variables: ["status"],
    updatedAt: "Jun 28, 2026",
  },
]

export const smsTemplateStore: CommunicationTemplateRecord[] = [
  {
    id: "1",
    type: "SMS",
    title: "Fee Reminder",
    subject: "Fee Payment Due — {month}",
    category: "Finance",
    lastUsed: "Aug 1, 2026",
    body: "Reminder: School fee payment for {month} is now due. Please pay promptly. - Finance Dept",
    variables: ["month"],
    updatedAt: "Aug 1, 2026",
  },
  {
    id: "2",
    type: "SMS",
    title: "Exam Result",
    subject: "Your Child's Exam Results Are Available",
    category: "Academic",
    lastUsed: "Jul 25, 2026",
    body: "Notification: Exam results have been uploaded to the portal. Please log in to view report card.",
    variables: [],
    updatedAt: "Jul 25, 2026",
  },
  {
    id: "3",
    type: "SMS",
    title: "Event Invitation",
    subject: "You're Invited: {event_name}",
    category: "Events",
    lastUsed: "Jul 10, 2026",
    body: "You are invited to {event_name}. We look forward to seeing you there! - School Admin",
    variables: ["event_name"],
    updatedAt: "Jul 10, 2026",
  },
  {
    id: "4",
    type: "SMS",
    title: "Leave Approval",
    subject: "Leave Application Status — {status}",
    category: "HR",
    lastUsed: "Jun 28, 2026",
    body: "HR Notice: Your leave application is {status}. Please check HR portal for full details.",
    variables: ["status"],
    updatedAt: "Jun 28, 2026",
  },
]

export const loginCredentialsStore: LoginCredentialRecord[] = [
  {
    id: "CRED-001",
    name: "Aarav Sharma",
    userId: "STD-2026-001",
    role: "Student",
    email: "aarav.s@student.school.edu",
    phone: "+91 98765 43210",
    lastSent: "Aug 1, 2026 10:00 AM",
    status: "Sent",
  },
  {
    id: "CRED-002",
    name: "Mr. Rajesh Sharma",
    userId: "PRN-2026-001",
    role: "Parent",
    email: "rajesh.sharma@gmail.com",
    phone: "+91 98765 43210",
    lastSent: "Aug 1, 2026 10:05 AM",
    status: "Sent",
  },
  {
    id: "CRED-003",
    name: "Dr. Amara Singh",
    userId: "STF-001",
    role: "Staff",
    email: "amara.singh@school.edu",
    phone: "+91 98765 11111",
    lastSent: "Jul 28, 2026 09:30 AM",
    status: "Sent",
  },
  {
    id: "CRED-004",
    name: "Zara Okafor",
    userId: "STD-2026-014",
    role: "Student",
    email: "zara.o@student.school.edu",
    phone: "+234 802 345 6789",
    lastSent: undefined,
    status: "Pending",
  },
  {
    id: "CRED-005",
    name: "Ms. Claire Fontaine",
    userId: "STF-002",
    role: "Staff",
    email: "claire.f@school.edu",
    phone: "+33 6 12 34 56 78",
    lastSent: "Jul 25, 2026 11:20 AM",
    status: "Sent",
  },
]
